name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init -input=false
        terraform apply -auto-approve -input=false

    - name: Generate Ansible Inventory
      run: |
        cd terraform
        echo "[web]" > ../ansible/inventory
        terraform output -raw public_ip >> ../ansible/inventory
        echo "" >> ../ansible/inventory
        cat ../ansible/inventory.tpl >> ../ansible/inventory
        cat ../ansible/inventory

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory playbook.yml